In [2]:
import numpy as np
np.__version__

'1.16.5'

In [3]:
a = np.array([1,2,3,4])
type(a)

numpy.ndarray

In [4]:
a

array([1, 2, 3, 4])

In [7]:
b = np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15]])


In [10]:
a.ndim


1

In [11]:
np.ndim(a)

1

In [12]:
a.shape, b.shape

((4,), (3, 5))

In [14]:
len(a.shape), len(b.shape)

(1, 2)

In [15]:
a.size, b.size

(4, 15)

In [16]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
range(1,11)

range(1, 11)

In [26]:
list(range(1,11,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
np.arange(1, 11, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [28]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [29]:
np.random.rand(2,3)

array([[7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01]])

In [30]:
np.random.rand(6,3)

array([[0.34556073, 0.39676747, 0.53881673],
       [0.41919451, 0.6852195 , 0.20445225],
       [0.87811744, 0.02738759, 0.67046751],
       [0.4173048 , 0.55868983, 0.14038694],
       [0.19810149, 0.80074457, 0.96826158],
       [0.31342418, 0.69232262, 0.87638915]])

In [33]:
np.random.randn()

1.9138203875690445

In [34]:
np.random.randn(2,3)

array([[ 0.33079713,  1.14194252, -1.12959516],
       [-0.85005238,  0.96082   , -0.21741818]])

In [36]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.shape

(3,)

In [39]:
b = np.array([[1,2,3], [4,5,6]])
b.shape

(2, 3)

In [40]:
len(b.shape)

2

In [42]:
b.shape[0] * b.shape[1]

6

In [43]:
b.size

6

In [44]:
a[1] = 9
a

array([1, 9, 3])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b[0][1]

2

In [48]:
b.shape

(2, 3)

In [49]:
b[0,1] = 9

In [50]:
b.reshape(3,2)

array([[1, 9],
       [3, 4],
       [5, 6]])

In [51]:
b.reshape(2,3)

array([[1, 9, 3],
       [4, 5, 6]])

In [52]:
b.reshape(1,6)

array([[1, 9, 3, 4, 5, 6]])

In [53]:
c=np.arange(18)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [54]:
c.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [55]:
c.reshape(2,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [56]:
c.reshape(9,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [57]:
c.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [58]:
c.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [60]:
c.reshape(2,-3)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [61]:
c.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [63]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
o = np.ones((3,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
f = np.full((3,4), 7)
f

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [69]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [74]:
d = np.array([1.5, 3.14, 2.1, 8])
d

array([1.5 , 3.14, 2.1 , 8.  ])

In [71]:
c = np.array([1,2,3,4], dtype=np.float64)
c

array([1., 2., 3., 4.])

In [72]:
c.dtype

dtype('float64')

In [76]:
a.astype(np.float32)

array([1., 9., 3.], dtype=float32)

In [77]:
a

array([1, 9, 3])

In [78]:
a = a.astype(np.float64)
a

array([1., 9., 3.])

In [82]:
np.zeros((3,4), dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [88]:
ls = list(range(10))
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
ls2 = []

for x in ls:
    ls2.append(x * 2)
    
ls2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [96]:
nls = np.arange(10)
nls

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
nls * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
nls2 = np.arange(12).reshape(3,4)
nls2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
nls2 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [103]:
a = np.arange(5)
b = np.arange(10, 15)
a, b

(array([0, 1, 2, 3, 4]), array([10, 11, 12, 13, 14]))

In [104]:
a + b

array([10, 12, 14, 16, 18])

In [106]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(2,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [107]:
a * b

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [108]:
b.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [109]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
a * b

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [112]:
a.dot(b.T)

array([[ 5, 14],
       [14, 50]])

In [113]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [114]:
a[3]

13

In [115]:
a[2:5]

array([12, 13, 14])

In [116]:
a[5:]

array([15, 16, 17, 18, 19])

In [117]:
a[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [121]:
a[1:8:2]

array([11, 13, 15, 17])

In [122]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [123]:
idx = [1,2,5,6,8]
a[idx]

array([11, 12, 15, 16, 18])

In [124]:
b = [False, True, True, False, False, True, False, True, True, True]
a[b]

array([11, 12, 15, 17, 18, 19])

In [125]:
a[[False, True, True, False, False, True, False, True, True, True]]

array([11, 12, 15, 17, 18, 19])

In [127]:
aa = a > 15
aa

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [128]:
a[aa]

array([16, 17, 18, 19])

In [129]:
a[a>15]

array([16, 17, 18, 19])

In [132]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a[1,1], a[0,2]

(5, 2)

In [137]:
a[2]

array([ 8,  9, 10, 11])

In [142]:
a[2,:]

"""0과 4는 처음과 끝이므로, :로 표현해서 다 가져온다."""

array([ 8,  9, 10, 11])

In [144]:
a[:,1]
"""모든 행에 걸려있는 1번째 요소 가져와"""

array([[1],
       [5],
       [9]])

In [146]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [147]:
a>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [148]:
a[a>6]

array([ 7,  8,  9, 10, 11])

In [149]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
np.where(a>3)

(array([1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [151]:
np.where(a>3, 1, 0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [154]:
np.where(a>5, 1, -100)

array([[-100, -100, -100, -100],
       [-100, -100,    1,    1],
       [   1,    1,    1,    1]])

In [155]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
a.sum()

66

In [158]:
a.mean()
"""평균"""

5.5

In [159]:
a.std()
"""표준편차"""

3.452052529534663

In [160]:
a.var()
"""분산"""

11.916666666666666

In [161]:
a.cumsum()
"""누적합"""

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [162]:
a.cumprod()
"""누적곱"""

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [163]:
b

[False, True, True, False, False, True, False, True, True, True]

In [164]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [165]:
a.sum(axis=1)

array([ 6, 22, 38])

In [166]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
a.sum()

66

In [168]:
np.random.rand(3,4)

array([[0.44789353, 0.9085955 , 0.29361415, 0.28777534],
       [0.13002857, 0.01936696, 0.67883553, 0.21162812],
       [0.26554666, 0.49157316, 0.05336255, 0.57411761]])

In [170]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
np.random.shuffle(a)

In [172]:
a

array([2, 5, 4, 7, 9, 6, 1, 8, 0, 3])

In [173]:
np.random.randint(0,10)

6

In [ ]:
np.random.randint(10,20,(3,4))

In [179]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
numpy.save("my.npy",a)

In [185]:
b = np.load("my.npy")
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
txt = np.loadtxt('my.txt')
txt

array([[10., 20., 30.],
       [40., 50., 60.]])